{"name": "test_error", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "@pytest.fixture\n    def error_fixture():\n>       assert 0\nE       assert 0\n\ntest.py:7: AssertionError"}, "start": 1702571584319, "stop": 1702571584319, "uuid": "a48db868-c2b3-4c9c-acd4-12db780f974d", "historyId": "ca90b281fdd8a99c5b0186544594feac", "testCaseId": "ca90b281fdd8a99c5b0186544594feac", "fullName": "test#test_error", "labels": [{"name": "suite", "value": "test"}, {"name": "host", "value": "byemen"}, {"name": "thread", "value": "33587-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test"}]}