{"name": "test_connexion", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_connexion():\n        try:\n>           assert z.connexion('impossible','impossible')\n\notherSteps/testMore.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \notherSteps/Ztrain.py:98: in connexion\n    WebDriverWait(driver, 20).until(EC.invisibility_of_element_located((By.XPATH,'/html/body/div[2]/div/div')))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"0ad6489a53259906419a82e184bbb766\")>, method = <function invisibility_of_element_located.<locals>._predicate at 0x7fb09e997c70>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py:95: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\n    def test_connexion():\n        try:\n            assert z.connexion('impossible','impossible')\n        except:\n>           assert False\nE           assert False\n\notherSteps/testMore.py:14: AssertionError"}, "start": 1703237042762, "stop": 1703237069287, "uuid": "51ffc843-bf63-453f-b605-57e41329a28b", "historyId": "4b8c4a8cf58e90c03e80b4fedf1937cd", "testCaseId": "4b8c4a8cf58e90c03e80b4fedf1937cd", "fullName": "otherSteps.testMore#test_connexion", "labels": [{"name": "parentSuite", "value": "otherSteps"}, {"name": "suite", "value": "testMore"}, {"name": "host", "value": "byemen"}, {"name": "thread", "value": "25386-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "otherSteps.testMore"}]}